services:
  ros-tutorial:
    build: .
    volumes:
      # Share X11 socket, does not work on Windows
      - /tmp/.X11-unix
      # Save code written in the container
      - ./code:/code
    environment:
      DISPLAY: "host.docker.internal:0"
